<a href="https://colab.research.google.com/github/ToyTeX/NumericalNotebooks/blob/main/ConditionNumber.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

print("=" * 70)
print("Matrix Perturbation Analysis")
print("=" * 70)
print()

# Define matrices and vectors
A = np.array([
    [10, 7, 8, 7],
    [7, 5, 6, 5],
    [8, 6, 10, 9],
    [7, 5, 9, 10]
], dtype=float)

x = np.array([1, 1, 1, 1], dtype=float)
b = np.array([32, 23, 33, 31], dtype=float)

A_perturbed = np.array([
    [10, 7, 8.1, 7.2],
    [7.08, 5.04, 6, 5],
    [8, 5.98, 9.89, 9],
    [6.99, 4.99, 9, 9.98]
], dtype=float)

x_perturbed = np.array([-81, 137, -34, 22], dtype=float)
b_perturbed = np.array([32, 23, 33, 31], dtype=float)

# Step 1: Verify the first equation Ax = b
print("Step 1: Verify the first equation Ax = b")
print("-" * 70)
print("Matrix A:")
print(A)
print("\nVector x:")
print(x)
print("\nComputing Ax:")
Ax = A @ x
print(Ax)
print("\nExpected b:")
print(b)
print("\nMaximum error:", np.max(np.abs(Ax - b)))
print("✓ First equation verified!")
print()

# Step 2: Verify the second equation (A + δA)(x + δx) = b
print("Step 2: Verify the second equation (A + δA)(x + δx) = b")
print("-" * 70)
print("Perturbed matrix (A + δA):")
print(A_perturbed)
print("\nPerturbed vector (x + δx):")
print(x_perturbed)
print("\nComputing (A + δA)(x + δx):")
A_perturbed_times_x_perturbed = A_perturbed @ x_perturbed
print(A_perturbed_times_x_perturbed)
print("\nExpected b:")
print(b_perturbed)
print("\nMaximum error:", np.max(np.abs(A_perturbed_times_x_perturbed - b_perturbed)))
print("✓ Second equation verified!")
print()

# Step 3: Compute perturbations
print("Step 3: Compute perturbations")
print("-" * 70)
deltaA = A_perturbed - A
deltaX = x_perturbed - x

print("Perturbation δA:")
print(deltaA)
print("\nPerturbation δx:")
print(deltaX)
print()

# Step 4: Compute norms and relative errors
print("Step 4: Compute norms and relative errors")
print("-" * 70)

# Infinity norms
norm_deltaX = np.linalg.norm(deltaX, np.inf)
norm_x_plus_deltaX = np.linalg.norm(x_perturbed, np.inf)
relative_x = norm_deltaX / norm_x_plus_deltaX

print(f"||δx||∞ = {norm_deltaX:.6f}")
print(f"||x + δx||∞ = {norm_x_plus_deltaX:.6f}")
print(f"||δx||∞ / ||x + δx||∞ = {relative_x:.8f}")
print()

norm_deltaA = np.linalg.norm(deltaA, np.inf)
norm_A = np.linalg.norm(A, np.inf)
relative_A = norm_deltaA / norm_A

print(f"||δA||∞ = {norm_deltaA:.6f}")
print(f"||A||∞ = {norm_A:.6f}")
print(f"||δA||∞ / ||A||∞ = {relative_A:.8f}")
print()

# Step 5: Compute condition number
print("Step 5: Compute condition number κ∞(A)")
print("-" * 70)

A_inv = np.linalg.inv(A)
print("Inverse of A:")
print(A_inv)
print()

norm_A_inv = np.linalg.norm(A_inv, np.inf)
condition_number = norm_A * norm_A_inv

print(f"||A||∞ = {norm_A:.6f}")
print(f"||A⁻¹||∞ = {norm_A_inv:.6f}")
print(f"κ∞(A) = ||A||∞ × ||A⁻¹||∞ = {condition_number:.6f}")
print()

# Alternative: use numpy's built-in condition number function
condition_number_numpy = np.linalg.cond(A, np.inf)
print(f"κ∞(A) using numpy.linalg.cond = {condition_number_numpy:.6f}")
print()

# Summary
print("=" * 70)
print("SUMMARY OF RESULTS")
print("=" * 70)
print(f"||δx||∞ / ||x + δx||∞ = {relative_x:.8f}")
print(f"||δA||∞ / ||A||∞     = {relative_A:.8f}")
print(f"κ∞(A)                = {condition_number:.8f}")
print("=" * 70)
print()



Matrix Perturbation Analysis

Step 1: Verify the first equation Ax = b
----------------------------------------------------------------------
Matrix A:
[[10.  7.  8.  7.]
 [ 7.  5.  6.  5.]
 [ 8.  6. 10.  9.]
 [ 7.  5.  9. 10.]]

Vector x:
[1. 1. 1. 1.]

Computing Ax:
[32. 23. 33. 31.]

Expected b:
[32. 23. 33. 31.]

Maximum error: 0.0
✓ First equation verified!

Step 2: Verify the second equation (A + δA)(x + δx) = b
----------------------------------------------------------------------
Perturbed matrix (A + δA):
[[10.    7.    8.1   7.2 ]
 [ 7.08  5.04  6.    5.  ]
 [ 8.    5.98  9.89  9.  ]
 [ 6.99  4.99  9.    9.98]]

Perturbed vector (x + δx):
[-81. 137. -34.  22.]

Computing (A + δA)(x + δx):
[32. 23. 33. 31.]

Expected b:
[32. 23. 33. 31.]

Maximum error: 1.1368683772161603e-13
✓ Second equation verified!

Step 3: Compute perturbations
----------------------------------------------------------------------
Perturbation δA:
[[ 0.    0.    0.1   0.2 ]
 [ 0.08  0.04  0.    0.  ]
 [ 